name: Add Issues and PRs to GitHub Project

on:
  issues:
    types:
      - opened
      - labeled
  pull_request:
    types:
      - opened
      - labeled

jobs:
  add-to-project:
    name: Add issue or PR to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/users/DavidDevPro/projects/10
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}
          # Vous pouvez ajouter des filtres de labels si nécessaire
          # labeled: bug, enhancement
          # label-operator: OR
